delivery/urls.py
from django.urls import path
from . import views

app_name = "delivery"
urlpatterns = [
    path("", views.CategoryView.as_view(), name="delivery"),
    path("filter/", views.filter_category, name="filter"),
    path("productpage/<int:id>", views.filter_product, name="productpage"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart, name="cart"),
    path("remove_from_cart/", views.remove_from_cart, name="remove_from_cart"),
    path("add_to_order/", views.add_to_order, name="add_to_order"),
    path("view_order/", views.View_Order.as_view(), name="view_order"),
    path("view_bill/<int:id>", views.view_bill, name="view_bill"),
    path("download_file/<int:id>", views.generatePDF, name="download_file"),
    path("paid/<int:id>", views.paid, name="paid"),
]

login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path("", views.loginUser, name="signin"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.UserRegister, name="register"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
]

mulberry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", include("delivery.urls")),
    path("admin/", admin.site.urls),
    path("login/", include("login.urls")),
    path("admins/", include("admins.urls")),
    path("product/", include("product.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/models.py
from django.db import models
from login.models import User
from product.models import Product
import datetime

# Create your models here.
class Order(models.Model):
    date_of_order = models.DateField(default=datetime.date.today)
    day = models.DateField(max_length=100)
    address = models.CharField(max_length=100)
    streetaddress = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    postal = models.IntegerField()
    country = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    total_price = models.DecimalField(max_digits=5, decimal_places=1)


class Order_details(models.Model):
    price = models.DecimalField(max_digits=5, decimal_places=1)
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

delivery/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from login.models import User, VendorInfo
from product.models import Categories, Product
from product.models import Offer
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.http import JsonResponse
from datetime import datetime as date, timedelta
from .models import Order, Order_details
from decimal import *
from django.http import HttpResponse
from mulberry.utils import render_to_pdf

# Create your views here.

# ----- CategoryView sends all the data from backend to main page -------
class CategoryView(TemplateView):
    template_name = "delivery.html"

    def get(self, request):

        # -- checks if user is logged-in or not, if user is logged in then we can see
        # -- username in the top navigation panel, we can click the name and see the user profile
        if request.session.has_key("user"):
            # extract session value to extract the user password from database
            semail = request.session["user"]

            # extract the user with matching email taken from session
            verifyUser = User.objects.filter(email=semail).first()

            # -- if the user logged in is super-admin or admin then he/she is
            # -- logged in another admin panel
            if verifyUser.admin or verifyUser.is_staff:
                return HttpResponseRedirect("../admins/admin")

        product = Product.objects.all()
        traders = User.objects.filter(is_staff=True, is_active=True)

        # -- just sending only four trader in main panel, after clicking view all we can see all restaurent
        trader = traders[0:4]
        offerss = Offer.objects.all()

        # -- only sending four product with offer
        offer = offerss[0:4]

        # -- sending different lists of for slider
        product1 = product[0:5]
        product2 = product[5:10]

        # -- checking whether there is an item in cart, if so show the no of items in cart
        if request.session.has_key("cart_count"):
            no_of_item_in_cart = request.session["cart_count"]
        else:
            no_of_item_in_cart = None

        # -- rendering all the data with the above information as dictionary
        return render(
            request,
            self.template_name,
            {
                "trader": trader,
                "product": product,
                "offer": offer,
                "product1": product1,
                "product2": product2,
                "traderss": traders,
                "cart_count": no_of_item_in_cart,
            },
        )


def filter_category(request):

    # -- if user selects offer or category and search for it
    # -- post data hits this url then this condition will work
    if request.method == "POST":

        # -- for searching according to category
        categoryid = request.POST.get("categoryid")

        # -- for searching according to offer
        offerid = request.POST.get("offerid")

        # -- if all is selected than all the restaurent is shown
        if categoryid == "all" or offerid == "all":
            trader = User.objects.filter(is_staff=True, is_active=True).order_by("id")
            selected_category = None
            total_trader_count = trader.count()
        # -- else only selected restaurent according to category is shown
        else:
            traders = []

            # -- if user wants to search according to category
            if categoryid:
                selected_category = Categories.objects.filter(id=categoryid).first()
                products = Product.objects.filter(category=categoryid)
                # -- trader with only selected category is shown
                for product in products:
                    traders.append(product.trader)

            # -- if user wants to search according to offer
            else:
                selected_category = Offer.objects.filter(id=offerid).first()
                offersss = Offer.objects.filter(id=offerid)
                for product in offersss:
                    traders.append(product.trader_offer)

            # -- converting the list containing trader to set so that same trader wont be saved for two times
            trade = set(traders)
            # -- again converting it to list becuase nopw we have filtered data, and its way easier to work with list
            trader = list(trade)

            count = 0
            for traders in trader:
                count = count + 1
            total_trader_count = count

        # paginaton code--------------------------
        paginator = Paginator(trader, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        # ----------------------------------------

        # -- if cart has food than it will show count of food else it will store none
        if request.session.has_key("cart_count"):
            no_of_item_in_cart = request.session["cart_count"]
        else:
            no_of_item_in_cart = None

        # -- to show in the tempalte, so that user can select the category
        category = Categories.objects.all()
        offerss = Offer.objects.all()
        offer = offerss[0:2]

        return render(
            request,
            "delivery/vendors.html",
            {
                "trader": page_obj,
                "category": category,
                "offer": offer,
                "selected_category": selected_category,
                "total_trader": total_trader_count,
                "cart_count": no_of_item_in_cart,
            },
        )
    # -- if user hits the url to show restaurent page than this part of code will send required
    # -- data
    else:
        product = Product.objects.all()
        trader = User.objects.filter(is_staff=True, is_active=True).order_by("id")
        total_trader_count = trader.count()
        category = Categories.objects.all()
        offerss = Offer.objects.all()
        offer = offerss[0:2]

        # paginaton code--------------------------
        paginator = Paginator(trader, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        # ----------------------------------------

        if request.session.has_key("cart_count"):
            no_of_item_in_cart = request.session["cart_count"]
        else:
            no_of_item_in_cart = None
        return render(
            request,
            "delivery/vendors.html",
            {
                "trader": page_obj,
                "product": product,
                "total_trader": total_trader_count,
                "category": category,
                "offer": offer,
                "cart_count": no_of_item_in_cart,
            },
        )


# -- when we hit this url we will get filtered restaurents
def filter_product(request, id):
    # -- if
    if request.method == "POST":
        categoryid = request.POST.get("categoryid")
        offerid = request.POST.get("offerid")

        if categoryid == "all" or offerid == "all":
            trader = User.objects.filter(is_staff=True, is_active=True).order_by("id")
            selected_category = None
            total_trader_count = trader.count()
        else:
            traders = []
            if categoryid:
                selected_category = Categories.objects.filter(id=categoryid).first()
                products = Product.objects.filter(category=categoryid)
                for product in products:
                    traders.append(product.trader)
            else:
                selected_category = Offer.objects.filter(id=offerid).first()
                offersss = Offer.objects.filter(id=offerid)
                for product in offersss:
                    traders.append(product.trader_offer)
            trade = set(traders)
            trader = list(trade)

            count = 0
            for traders in trader:
                count = count + 1
            total_trader_count = count
        # paginaton code--------------------------
        paginator = Paginator(trader, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        # ----------------------------------------
        category = Categories.objects.all()
        offerss = Offer.objects.all()
        offer = offerss[0:2]
        return render(
            request,
            "delivery/productpage.html",
            {
                "trader": page_obj,
                "category": category,
                "offer": offer,
                "selected_category": selected_category,
                "total_trader": total_trader_count,
            },
        )
    else:
        sort = request.GET.get("sort")
        if sort:
            product = Product.objects.filter(trader_id=id).order_by(sort)
        else:
            product = Product.objects.filter(trader_id=id)
        total_trader_count = product.count()
        user = VendorInfo.objects.filter(user_id=id).first()
        trader = User.objects.filter(id=id).first()
        if request.session.has_key("cart_count"):
            no_of_item_in_cart = request.session["cart_count"]
        else:
            no_of_item_in_cart = None
        # paginaton code--------------------------
        paginator = Paginator(product, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        # ----------------------------------------

        category = Categories.objects.all()
        offer = Offer.objects.all()

        return render(
            request,
            "delivery/productpage.html",
            {
                "product": page_obj,
                "user_info": user,
                "total_trader": total_trader_count,
                "category": category,
                "offer": offer,
                "trader": trader,
                "cart_count": no_of_item_in_cart,
            },

templates/delivery/vendors.html
{%extends '../base.html' %}{% load static%}
{%block csspart%}
<link rel="stylesheet" href="{% static '/css/vendors.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<link crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
    referrerpolicy="no-referrer" rel="stylesheet" />
<link href="{%static 'assets/css/theme.css' %}" rel="stylesheet" />

<style>
    .text-lg-center {
        padding-left: 5px;
    }

    .bg-light {
        background-color: #373d4f !important;
    }

    .fabb {
        font-size: 40px;
        color: white;
        padding-left: 5px;
    }

    .pe-2 {
        padding-left: 0.8rem !important;
    }

    .img-thumbnail {
        max-width: 50px;
    }

    .profilepic img {
        width: 300px;
        /* You can set the dimensions to whatever you want */
        height: 300px;
        object-fit: cover;
    }

    .foodimg img {
        width: 200px;
        /* You can set the dimensions to whatever you want */
        height: 200px;
        object-fit: cover;
    }

    .shownimage img {
        width: 350px;
        /* You can set the dimensions to whatever you want */
        height: 250px;
        object-fit: cover;
    }

    .fs-2 {
        font-size: 2rem !important;
    }

    section {
        padding-top: 0.5rem;
    }

    .pagination {
        display: inline-block;
        width: 80%;
        margin-left: 40%;
    }

    .pagination a {
        color: black;
        float: left;
        padding: 8px 16px;
        text-decoration: none;
        transition: background-color .3s;
        border: 1px solid #ddd;
    }

    .pagination a.active {
        background-color: #4CAF50;
        color: white;
        border: 1px solid #4CAF50;
    }

    .pagination a:hover:not(.active) {
        background-color: #ddd;
    }
</style>
{%endblock csspart%}

<body>
    {%block body%}
    <br>
    <br>
    <br>
    <div class="filter"> <button class="btn btn-default" type="button" data-toggle="collapse"
            data-target="#mobile-filter" aria-expanded="true" aria-controls="mobile-filter">Filters<span
                class="fa fa-filter pl-1"></span></button>
    </div>
    <!-- Mobile view -->
    <!--
    <div id="mobile-filter">
        <p class="pl-sm-0 pl-2"> Home | <b>All Breads</b></p>
        <div class="border-bottom pb-2 ml-2">
            <h4 id="burgundy">Filters</h4>
        </div>
        <div class="py-2 border-bottom ml-3">
            <h6 class="font-weight-bold">Categories</h6>
            <div id="orange"><span class="fa fa-minus"></span></div>
            <form>
                <div class="form-group"> <input type="checkbox" id="artisan"> <label for="artisan">Fresh Artisan
                        Breads</label> </div>
                <div class="form-group"> <input type="checkbox" id="breakfast"> <label for="breakfast">Breakfast
                        Breads</label> </div>
                <div class="form-group"> <input type="checkbox" id="healthy"> <label for="healthy">Healthy
                        Breads</label>
                </div>
            </form>
        </div>
        <div class="py-2 border-bottom ml-3">
            <h6 class="font-weight-bold">Accompainments</h6>
            <div id="orange"><span class="fa fa-minus"></span></div>
            <form>
                <div class="form-group"> <input type="checkbox" id="tea"> <label for="tea">Tea Cakes</label> </div>
                <div class="form-group"> <input type="checkbox" id="cookies"> <label for="cookies">Cookies</label>
                </div>
                <div class="form-group"> <input type="checkbox" id="pastries"> <label for="pastries">Pastries</label>
                </div>
                <div class="form-group"> <input type="checkbox" id="dough"> <label for="dough">Cookie Dough</label>
                </div>
                <div class="form-group"> <input type="checkbox" id="choco"> <label for="choco">Chocolates</label> </div>
            </form>
        </div>
        <div class="py-2 ml-3">
            <h6 class="font-weight-bold">Top Offers</h6>
            <div id="orange"><span class="fa fa-minus"></span></div>
            <form>
                <div class="form-group"> <input type="checkbox" id="25off"> <label for="25">25% off</label> </div>
                <div class="form-group"> <input type="checkbox" id="5off"> <label for="5off" id="off">5% off on artisan
                        breads</label> </div>
            </form>
        </div>
    </div> -->
    <!-- Sidebar filter section -->
    <section id="sidebar">
        {% if not selected_category%}
        <p> Home | <b>All Restaurants</b></p>
        {%else%}
        <p> Home | <b>{{selected_category.name}}</b></p>
        {%endif%}
        <div class="border-bottom pb-2 ml-2">
            <h4 id="burgundy">Filters</h4>
        </div>
        <div class="py-2 border-bottom ml-3">
            <h6 class="font-weight-bold">Categories</h6>
            <div id="orange"><span class="fa fa-minus"></span></div>
            <form method="POST" action="{% url 'delivery:filter'%}">
                {% csrf_token %}
                {% for categories in category%}
                {%if selected_category.id == categories.id%}
                <div class="form-group"><input type="radio" value="{{categories.id}}" id="{{categories.id}}"
                        name="categoryid" checked>
                    <label for="{{categories.id}}">{{categories.name}}</label>
                </div>
                {%else%}
                <div class="form-group"><input type="radio" value="{{categories.id}}" id="{{categories.id}}"
                        name="categoryid">
                    <label for="{{categories.id}}">{{categories.name}}</label>
                </div>
                {%endif%}
                {%endfor%}
                {%if not selected_category%}
                <div class="form-group"><input type="radio" value="all" name="categoryid" checked>
                    <label for="categoryid">All Restaurants</label>
                </div>
                {%else%}
                <div class="form-group"><input type="radio" value="all" name="categoryid">
                    <label for="categoryid">All Restaurants</label>
                </div>
                {%endif%}
                <input type="submit" value="Done">
        </div>
        </form>
        </div>

        <div class="py-2 border-bottom  ml-3">
            <h6 class="font-weight-bold">Top Offers</h6>
            <div id="orange"><span class="fa fa-minus"></span></div>
            <form method="POST" action="{% url 'delivery:filter'%}">
                {% csrf_token %}
                {% for offers in offer%}
                {%if selected_category.id == offers.id%}
                <div class="form-group"> <input type="radio" name="offerid" value="{{offers.id}}" id="{{offers.id}}"
                        checked>
                    <label for="{{offers.id}}">£
                        {{offers.offer_amount}} off</label>
                </div>
                {%else%}
                <div class="form-group"> <input type="radio" name="offerid" value="{{offers.id}}" id="{{offers.id}}">
                    <label for="{{offers.id}}">£
                        {{offers.offer_amount}} off</label>
                </div>
                {%endif%}
                {%endfor%}
                <input type="submit" value="Done">
            </form>
        </div>
    </section>
    <!-- products section -->
    <section id="products">
        <div class="container">
            <div class="d-flex flex-row">
                <div class="text-muted m-2" id="res">Showing {{total_trader}} results</div>
            </div>
            <section id="testimonial">
                <div class="container">
                    <div class="row h-100">
                        <div class="col-lg-7 mx-auto text-center mb-6">
                            <h5 class="fw-bold fs-3 fs-lg-5 lh-sm mb-3">
                                Featured Restaurants
                            </h5>
                        </div>
                    </div>
                    <div class="row gx-2">
                        {% for traders in trader%}
                        {%if traders.is_active %}
                        <div class="col-sm-6 col-md-4 col-lg-3 h-100 mb-5">
                            <a href="{% url 'delivery:productpage' traders.id %}">
                                <div class="card card-span h-100 text-white rounded-3">
                                    <div class="profilepic">
                                        <img class="img-fluid rounded-3" src="{{traders.profile_pic.url}}" alt="..." />

                                    </div>
                                    <div class="card-img-overlay ps-0">
                                        <span class="badge bg-danger p-2 ms-3"><i class="fas fa-tag me-2 fs-0"></i><span
                                                class="fs-0">20%
                                                off</span></span><span class="badge bg-primary ms-2 me-1 p-2"><i
                                                class="fas fa-clock me-1 fs-0"></i><span class="fs-0">Fast</span></span>
                                    </div>
                                    <div class="card-body ps-0">
                                        <div class="d-flex align-items-center mb-3">
                                            <img class="img-thumbnail" src="{{traders.profile_pic.url}}" alt="" />
                                            <div class="flex-1 ms-3">
                                                <h5 class="mb-0 fw-bold text-1000">{{traders.first_name}}</h5>
                                                <span class="text-primary fs--1 me-1"><i
                                                        class="fas fa-star"></i></span><span
                                                    class="mb-0 text-primary">46</span>
                                            </div>
                                        </div>
                                        <span class="text-warning me-2"><i
                                                class="fas fa-map-marker-alt"></i></span><span
                                            class="text-primary">{{traders.address}}</span>
                                        <span class="badge bg-soft-danger p-2"><span
                                                class="fw-bold fs-1 text-danger">Opens
                                                Tomorrow</span></span>
                                    </div>
                                </div>
                            </a>

                        </div>
                        {% endif %}
                        {%endfor%}

                    </div>

                    <div class="pagination">
                        <span>

                            {%if trader.has_previous%}
                            <a href="?page={{trader.previous_page_number}}"> Previous </a>
                            {%endif%}

                            <a><span>{{trader.number}}</span></a>

                            {%if trader.has_next%}
                            <a href="?page={{trader.next_page_number}}"> Next </a>
                            {%endif%}

                        </span>

                    </div>
                </div>
            </section>
        </div>
    </section>
    {%endblock body%}
    {%block footer%}
    {%endblock footer%}
</body>

</html>