delivery/urls.py
from django.urls import path
from . import views

app_name = "delivery"
urlpatterns = [
    path("", views.CategoryView.as_view(), name="delivery"),
    path("filter/", views.filter_category, name="filter"),
    path("productpage/<int:id>", views.filter_product, name="productpage"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart, name="cart"),
    path("remove_from_cart/", views.remove_from_cart, name="remove_from_cart"),
    path("add_to_order/", views.add_to_order, name="add_to_order"),
    path("view_order/", views.View_Order.as_view(), name="view_order"),
    path("view_bill/<int:id>", views.view_bill, name="view_bill"),
    path("download_file/<int:id>", views.generatePDF, name="download_file"),
    path("paid/<int:id>", views.paid, name="paid"),
]

login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path("", views.loginUser, name="signin"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.UserRegister, name="register"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
]

mulberry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", include("delivery.urls")),
    path("admin/", admin.site.urls),
    path("login/", include("login.urls")),
    path("admins/", include("admins.urls")),
    path("product/", include("product.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/models.py
from django.db import models
from login.models import User
from product.models import Product
import datetime

# Create your models here.
class Order(models.Model):
    date_of_order = models.DateField(default=datetime.date.today)
    day = models.DateField(max_length=100)
    address = models.CharField(max_length=100)
    streetaddress = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    postal = models.IntegerField()
    country = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    total_price = models.DecimalField(max_digits=5, decimal_places=1)


class Order_details(models.Model):
    price = models.DecimalField(max_digits=5, decimal_places=1)
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

delivery/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from login.models import User, VendorInfo
from product.models import Categories, Product
from product.models import Offer
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.http import JsonResponse
from datetime import datetime as date, timedelta
from .models import Order, Order_details
from decimal import *
from django.http import HttpResponse
from mulberry.utils import render_to_pdf

# Create your views here.

# ----- CategoryView sends all the data from backend to main page -------
class CategoryView(TemplateView):
    template_name = "delivery.html"

    def get(self, request):

        # -- checks if user is logged-in or not, if user is logged in then we can see
        # -- username in the top navigation panel, we can click the name and see the user profile
        if request.session.has_key("user"):
            # extract session value to extract the user password from database
            semail = request.session["user"]

            # extract the user with matching email taken from session
            verifyUser = User.objects.filter(email=semail).first()

            # -- if the user logged in is super-admin or admin then he/she is
            # -- logged in another admin panel
            if verifyUser.admin or verifyUser.is_staff:
                return HttpResponseRedirect("../admins/admin")

        product = Product.objects.all()
        traders = User.objects.filter(is_staff=True, is_active=True)

        # -- just sending only four trader in main panel, after clicking view all we can see all restaurent
        trader = traders[0:4]
        offerss = Offer.objects.all()

        # -- only sending four product with offer
        offer = offerss[0:4]

        # -- sending different lists of for slider
        product1 = product[0:5]
        product2 = product[5:10]

        # -- checking whether there is an item in cart, if so show the no of items in cart
        if request.session.has_key("cart_count"):
            no_of_item_in_cart = request.session["cart_count"]
        else:
            no_of_item_in_cart = None

        # -- rendering all the data with the above information as dictionary
        return render(
            request,
            self.template_name,
            {
                "trader": trader,
                "product": product,
                "offer": offer,
                "product1": product1,
                "product2": product2,
                "traderss": traders,
                "cart_count": no_of_item_in_cart,
            },
        )


def filter_category(request):

    # -- if user selects offer or category and search for it
    # -- post data hits this url then this condition will work
    if request.method == "POST":

        # -- for searching according to category
        categoryid = request.POST.get("categoryid")

        # -- for searching according to offer
        offerid = request.POST.get("offerid")

        # -- if all is selected than all the restaurent is shown
        if categoryid == "all" or offerid == "all":
            trader = User.objects.filter(is_staff=True, is_active=True).order_by("id")
            selected_category = None
            total_trader_count = trader.count()
        # -- else only selected restaurent according to category is shown
        else:
            traders = []

            # -- if user wants to search according to category
            if categoryid:
                selected_category = Categories.objects.filter(id=categoryid).first()
                products = Product.objects.filter(category=categoryid)
                # -- trader with only selected category is shown
                for product in products:
                    traders.append(product.trader)

            # -- if user wants to search according to offer
            else:
                selected_category = Offer.objects.filter(id=offerid).first()
                offersss = Offer.objects.filter(id=offerid)
                for product in offersss:
                    traders.append(product.trader_offer)

            # -- converting the list containing trader to set so that same trader wont be saved for two times
            trade = set(traders)
            # -- again converting it to list becuase nopw we have filtered data, and its way easier to work with list
            trader = list(trade)

            count = 0
            for traders in trader:
                count = count + 1
            total_trader_count = count

        # paginaton code--------------------------
        paginator = Paginator(trader, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        # ----------------------------------------

        # -- if cart has food than it will show count of food else it will store none
        if request.session.has_key("cart_count"):
            no_of_item_in_cart = request.session["cart_count"]
        else:
            no_of_item_in_cart = None

        # -- to show in the tempalte, so that user can select the category
        category = Categories.objects.all()
        offerss = Offer.objects.all()
        offer = offerss[0:2]

        return render(
            request,
            "delivery/vendors.html",
            {
                "trader": page_obj,
                "category": category,
                "offer": offer,
                "selected_category": selected_category,
                "total_trader": total_trader_count,
                "cart_count": no_of_item_in_cart,
            },
        )
    # -- if user hits the url to show restaurent page than this part of code will send required
    # -- data
    else:
        product = Product.objects.all()
        trader = User.objects.filter(is_staff=True, is_active=True).order_by("id")
        total_trader_count = trader.count()
        category = Categories.objects.all()
        offerss = Offer.objects.all()
        offer = offerss[0:2]

        # paginaton code--------------------------
        paginator = Paginator(trader, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        # ----------------------------------------

        if request.session.has_key("cart_count"):
            no_of_item_in_cart = request.session["cart_count"]
        else:
            no_of_item_in_cart = None
        return render(
            request,
            "delivery/vendors.html",
            {
                "trader": page_obj,
                "product": product,
                "total_trader": total_trader_count,
                "category": category,
                "offer": offer,
                "cart_count": no_of_item_in_cart,
            },
        )


# -- when we hit this url we will get filtered restaurents
def filter_product(request, id):
    # -- if
    if request.method == "POST":
        categoryid = request.POST.get("categoryid")
        offerid = request.POST.get("offerid")

        if categoryid == "all" or offerid == "all":
            trader = User.objects.filter(is_staff=True, is_active=True).order_by("id")
            selected_category = None
            total_trader_count = trader.count()
        else:
            traders = []
            if categoryid:
                selected_category = Categories.objects.filter(id=categoryid).first()
                products = Product.objects.filter(category=categoryid)
                for product in products:
                    traders.append(product.trader)
            else:
                selected_category = Offer.objects.filter(id=offerid).first()
                offersss = Offer.objects.filter(id=offerid)
                for product in offersss:
                    traders.append(product.trader_offer)
            trade = set(traders)
            trader = list(trade)

            count = 0
            for traders in trader:
                count = count + 1
            total_trader_count = count
        # paginaton code--------------------------
        paginator = Paginator(trader, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        # ----------------------------------------
        category = Categories.objects.all()
        offerss = Offer.objects.all()
        offer = offerss[0:2]
        return render(
            request,
            "delivery/productpage.html",
            {
                "trader": page_obj,
                "category": category,
                "offer": offer,
                "selected_category": selected_category,
                "total_trader": total_trader_count,
            },
        )
    else:
        sort = request.GET.get("sort")
        if sort:
            product = Product.objects.filter(trader_id=id).order_by(sort)
        else:
            product = Product.objects.filter(trader_id=id)
        total_trader_count = product.count()
        user = VendorInfo.objects.filter(user_id=id).first()
        trader = User.objects.filter(id=id).first()
        if request.session.has_key("cart_count"):
            no_of_item_in_cart = request.session["cart_count"]
        else:
            no_of_item_in_cart = None
        # paginaton code--------------------------
        paginator = Paginator(product, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        # ----------------------------------------

        category = Categories.objects.all()
        offer = Offer.objects.all()

        return render(
            request,
            "delivery/productpage.html",
            {
                "product": page_obj,
                "user_info": user,
                "total_trader": total_trader_count,
                "category": category,
                "offer": offer,
                "trader": trader,
                "cart_count": no_of_item_in_cart,
            },

templates/acc_active_email.html
{% load static %} {% autoescape off %} Hi {{ user.first_name }}, Please click on
the link to confirm your registration,
http://{{ domain }}{% url 'login:activate' uidb64=uid token=token %} {% endautoescape %}

templates/acc_for_vendor.html
{% load static %} {% autoescape off %} Hi {{ user.first_name }} welcomw to FOODWAGOn
        your login credentials for foodwagon food delivery
        username: {{username}}
        password:{{password}}

        click on this link to login
        http://{{ domain }}{% url 'login:signin' %} {% endautoescape %}

templates/sign_in.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Mulberry</title>
  <!-- Font Icon -->
  <link rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}" />
  <!-- Main css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
  <div class="main">
    <!-- Sing in  Form -->
    <section class="sign-in">
      <div class="container">

        <div class="signin-content">

          <div class="signin-image">
            <figure>
              <img src="{% static 'image/vendor-signin.jpg' %}" alt="sing up image" />
            </figure>
            <a href="{% url 'login:register' %}" class="signup-image-link">Create an account</a>
          </div>

          <div class="signin-form">
            <div>
              {% for message in messages %}
              <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
              </div>
              {% endfor %}
            </div>
            <h2 class="form-title">Sign in</h2>
            <form class="register-form" id="login-form" novalidate>
              {% csrf_token %}
              <div class="form-group">
                <label for="your_name"><i class="nav-icon fas fa-edit"></i></label>
                {{form.email}}
              </div>
              <div class="form-group">
                <label for="your_pass"><i class="fas fa-unlock"></i></i></label>
                {{form.password}}
              </div>
              <div class="form-group">
                {{form.rememberMe}}
                <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
              </div>
              <div class="form-group form-button">
                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in" />
              </div>
            </form>
            <div class="social-login">
              <span class="social-label">Or login with</span>
              <ul class="socials">
                <li>
                  <a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a>
                </li>
                <li>
                  <a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </section>
  </div>

  <!-- JS -->
  <script src="{%static 'js/jquery.min.js' %}"></script>
  <script src="{%static 'js/main.js' %}"></script>
  <script src="https://kit.fontawesome.com/b45233a9f7.js" crossorigin="anonymous"></script>
  <script src="{% static 'js/ajax/actions.js'%}"></script>
  <script src="http://code.jquery.com/jquery-3.4.0.min.js"
    integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>
  <script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
<!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

templates/sign_up.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Mulberry</title>

    <!-- Font Icon -->
    <link
      rel="stylesheet"
      href="{% static 'css/material-design-iconic-font.min.css' %}"
    />
    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <div class="main">
      <!-- Sign up form -->
      <section class="signup">
        <div class="container">
          <div class="signup-content">

            <div class="signup-form">
              <h2 class="form-title">Sign up</h2>
              <form class="register-form" id="register-form" novalidate>
              {% csrf_token %}
                <div class="form-group">
                  <label for="name"><i class="nav-icon fas fa-edit"></i></label>
                    {{form.first_name}}
                </div>
                <div class="form-group">
                  <label for="email"
                    ><i class="far fa-envelope-open"></i
                  ></label>
                {{form.email}}
                </div>
          
                <div class="form-group">
                  <label for="address"
                    ><i class="far fa-address-book"></i></label>
                {{form.address}}
                </div>

                <div class="form-group">
                  <label for="pass"><i class="fas fa-unlock"></i></label>
                {{form.password}}
                </div>
                <div class="form-group">
                  <label for="re-pass"
                    ><i class="fas fa-key"></i></i
                  ></label>
                  {{form.re_pass}}
                </div>
                <div class="form-group">
                {{form.terms}}
                  <label for="agree-term" class="label-agree-term"
                    ><span><span></span></span>I agree all statements in
                    <a href="#" class="term-service">Terms of service</a></label
                  >
                </div>
                <div class="form-group form-button">
                  <input
                    type="submit"
                    name="signup"
                    id="signup"
                    class="form-submit"
                    value="Register"
                  >
                </div>
                </form>
            </div>
            <div class="signup-image">
              <figure>
                <img
                  src="{% static 'image/vendor-signup.png' %}"
                  alt="sing up image"
                />
              </figure>
              <a href="{% url 'login:signin' %}" class="signup-image-link">I am already member</a>
            </div>
          </div>
        </div>
      </section>
    </div>

    <!-- JS -->
    <script src="{%static 'js/jquery.min.js' %}"></script>
    <script src="{%static 'js/main.js' %}"></script>
    <script
      src="https://kit.fontawesome.com/b45233a9f7.js"
      crossorigin="anonymous"
    ></script>
    <script  src="{% static 'js/ajax/actions.js'%}"></script>  
    <script src="http://code.jquery.com/jquery-3.4.0.min.js" integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>  
  </body>
  <!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>